Promise的构造函数，以及被then调用执行的函数基本上都可以认为是在try...catch代码块中执行的，所以在这些代码中即使使用throw，程序本身也不会因为异常而终止。

如果在Promise中使用throw语句的话，会被try...catch住，最终promise对象也变为Rejected状态。
